spring:
  application:
    name: hhplus-concert
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert
    username: concert
    password: concert1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: localhost
      port: 6379
concert:
  limit:
    processCount: 50
  queueKey: 'concert-waiting-queue'


server:
  port: 8080

logging:
  level:
    com.hhplusconcert: info
---
spring:
  application:
    name: hhplus-concert
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert_test
    username: concert_test
    password: concert_test1234
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
concert:
  limit:
    processCount: 50
  queueKey: 'concert-waiting-queue-test'


server:
  port: 8080

logging:
  level:
    com.hhplusconcert: info
