spring:
  application:
    name: hhplus-concert
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert
    username: concert
    password: concert1234
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080

logging:
  level:
    com.hhplusconcert: info
